### ISSUE TITLE
Bulk Data Loads are not closed after upload

### ISSUE THREAD

**Issue by andrehertwig** [georgwittberger/sfdx-data-deploy-plugin#11]
When an upload has been finished (with or without success), the Bulk Data Load Jobs are still "In Progress" 
https://<yourDomain>.lightning.force.com/lightning/setup/AsyncApiJobStatus/home

Would be good if they could be closed afterwards

**Comment by georgwittberger** [comment]
Thanks for reporting this issue, André. It'll be fixed with the next bugfix release.
