### ISSUE TITLE
Retrieve the "Id" field and lookups

### ISSUE THREAD

**Issue by dweaver33** [georgwittberger/sfdx-data-deploy-plugin#12]
I'm unable to retrieve the standard "Id" field for any object and as such, unable to reference the field as a lookup.  

Is there any way, other than creating a customer external ID field?

For example: If you retrieve contacts, it would be nice to have the AccountId field included and be able to use it as reference to the Id field on Account.

**Comment by georgwittberger** [comment]
The system field `Id` is always discarded when retrieving data for good reasons. The record ID is specific to the Salesforce organization. Therefore, it is discouraged to use this field as a pseudo-external ID to upsert records in a different organization.

Nevertheless, I understand your wish to have control over the behavior. I will try to take some time soon to add a configuration option allowing you to disable pruning of system fields.

Meanwhile, you could build your own patched plugin version by modifying this file:

https://github.com/georgwittberger/sfdx-data-deploy-plugin/blob/master/src/modules/datadeploy/retrieve/delete-system-fields.ts

**Comment by dweaver33** [comment]
Hi, actually forked and did as you said.  Or rather, I basically ignore the "delete-system-fields" file if the user explicitly sets the columns they want.   

Basically, this bit of code in the retrieve-data.ts file:
`          if (query.select.toString() == '*') {
            deleteSystemFields(record);
          }`

**Comment by georgwittberger** [comment]
As of version 2.5.0 you can set `excludeSystemFields: false` in the retrieve config of a job to preserve system fields in the retrieved data. You can then still exclude some of those fields using `excludeFieldApiNames`.
