### ISSUE TITLE
retrieveConfig.maxRecordCount is limited to 500

### ISSUE THREAD

**Issue by andrehertwig** [georgwittberger/sfdx-data-deploy-plugin#3]
Hi
I tried to set the retrieveConfig.maxRecordCount greater than 500 but always 500 entries will be retrieved at maximum.
lowing the maxRecordCount e.g. to 20 will work as expected.

affected version 2.3.0

**Comment by georgwittberger** [comment]
The maximum number of records returned per query seems to be 500 as described in this documentation:

https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_querymore.htm

We can try enabling `autoFetch` for the query to load more records at once:

http://jsforce.github.io/jsforce/doc/Query.html#execute
