### ISSUE TITLE
Import will abort with no message when import file is empty

### ISSUE THREAD

**Issue by andrehertwig** [georgwittberger/sfdx-data-deploy-plugin#5]
When the json file to import is an empty list, the import breaks without any error message.
Maybe not really a bug, but I would expect to see a message like "skip import <object> 0 items to import" or something like this and the import process will go on

Also the _deployConfig.failOnError=false_ does not work in this case.

**Comment by georgwittberger** [comment]
Yes, I agree. This is caused by insufficient error handling when executing the Bulk API batch. The API does not allow the execution of batches with no records.

The plugin should better evaluate the input records array and simply skip the whole job if it does not contain any records. I'll fix this.
