### ISSUE TITLE
Jenkins deployment fails because of json output

### ISSUE THREAD

**Issue by uwedd** [georgwittberger/sfdx-data-deploy-plugin#6]
The jenkins triggered build fails if the json output is not disabled in sfdx options.
Example:
`{
  "status": 0,
  "result": {
    "deploymentDirectory": "/deploydir",
    "jobResults": [
      {
        "sObjectApiName": "ccrz__E_Configuration__c",
        "operation": "upsert",
        "dataFileName": "Configuration.json",
        "deployedRecordsCount": 9,
        "failedRecordsCount": 0
      }
    ]
  }
}

Finished: FAILURE`

The sfdx datadeploy toll is using this.log() for logging. The output is not suppressed for logging, if the tool is not used with options --json. We have got a hint that this.ux.log() would solve the issue.

**Comment by georgwittberger** [comment]
Hi Uwe, thanks for reporting this issue and providing a solution hint. I'll try to fix this as soon as possible by using `this.ux.log()` for all the normal log messages.
