### ISSUE TITLE
FeatureRequest: Deactivate ApexTrigger on deploy

### ISSUE THREAD

**Issue by andrehertwig** [georgwittberger/sfdx-data-deploy-plugin#8]
For some reason it would be useful to be able to deactivate triggers before deploying data to a specific object.

```javascript
"deployConfig": {
    "deactiveTriggers": [
         "trigger1", 
         "trigger2"
    ]
}
```

with SFDX it is possible to retrieve a trigger
```
sfdx force:source:retrieve -m ApexTrigger:trigger1
```
the "status" in metadata.xml can be set to "Inactive" before deploying and to active afterwards

**Comment by georgwittberger** [comment]
This SFDX plugin is dedicated to handling the data transfer only. If some specific configuration must be set up in the target Salesforce org before deploying data another SFDX command should be used for that.

See the SFPowerKit plugin made by Accenture which offers commands to activate and deactivate triggers: https://github.com/Accenture/sfpowerkit/blob/master/README.md#sfpowerkitorgtriggerdeactivate

You can orchestrate the whole data import procedure using a shell script which first deactivates the trigger using SFPowerKit, then transfers the data using my plugin and then activates the trigger again.
